# Base configs
baseurl: ""

# UI configs
title: "Biswajit Behera"
author: "Biswajit Behera"
about: "A Programmer"
social_urls:
  facebook: "https://www.facebook.com/mistryvatsal"
  twitter: "https://www.twitter.com/mistryvatsal11"
  instagram: "https://www.instagram.com/kartabyam"
  github: "https://www.biswajit976.github.io"
